@URL = http://localhost:55555/api

###
GET {{URL}}/prices
Content-Type: application/json

###
GET  {{URL}}/availableservices
Content-Type: application/json

###
GET {{URL}}/prices/GetByOk/tym razem ok
Content-Type: application/json
###
GET {{URL}}/prices/15
Content-Type: application/json

###
POST {{URL}}/prices
Content-Type: application/json
api-key: employee-secret

{
  "id": 0,
  "priceValue": 15,
  "currency": "PLN"
}
###
PUT {{URL}}/prices/15
Content-Type: application/json
api-key: employee-secret

{
  "id": 15,
  "priceValue": 750,
  "currency": "PLN"
}

###
DELETE {{URL}}/prices/13333
###
POST {{URL}}/availableservices
Content-Type: application/json

{
  "id": 0,
  "name": "Fryzjer 2"  
}
###
GET {{URL}}/servicetypes/
Content-Type: application/json
###
GET  {{URL}}/availableservices
Content-Type: application/json